export const BOOKING_START = 'BOOKING_START';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const BOOKING_FAILED = 'BOOKING_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REDIRECT = 'AUTH_REDIRECT';
